### ISSUE TITLE
Final versions thread!

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow#1]
When you've decided your max patch, score, and recording are finished (i.e. working and ready to be handed off to someone else), please post the following here:

Repo name (repo you're currently assigned to)
Commit hash 
Name of instrument
Score Title
Recording Title

i.e. 
- repo1
- 5973d9de8cab1c256fccb625ff650d2ae86a4e31
- oatmealSynth
- I Prefer My Splines Reticulated, Will
- Reverse Bow & Arrow

**Note**, github automatically converts 40-character hashes into 7-character. Don't be worried if this happens here :)

### if you need to find the right commit hash:
```shell
git log
```
Locate the commit you want (it might likely be the most-recent), copy the entire 40-character hash.

**Comment by michaelpalumbo** [comment]
- gitshow4
- 08fab124f1cecb4eea78e0bef6744818571faae9
- Salty Moustache
- "Score"
- "gitshow4.wav"

**Comment by roryhoy** [comment]
- gitShow5

- c4aeca6a2818b04f87ad040b44140015af0f23da

- Crystal Cave

- "Score"

- "I Seem to Have Come Across a Crystal Cave.aif"

**Comment by kieranmaraj** [comment]
- gitShow3

- 97d546abd91963e60fed2cd940e37d4134e0fc3d

- Tumble

- Score

- "Trying to be Mark Fell.aif"

**Comment by michaelpalumbo** [comment]
Thanks!

**Comment by TheDispersionLab** [comment]
I’m going to try to be Kieran Maraj today - I see that it is up for grabs.

**Comment by michaelpalumbo** [comment]
Were I to jump on that train I suppose the resulting recording could be titled "I’m going to try to be Kieran Maraj.m3u"

**Comment by roryhoy** [comment]
- gitShow6

- eb88a83c3a325c0a47fe41fe856786bb9e14c672

- Harbinger

- Score

- Transmission.aif

**Comment by kieranmaraj** [comment]
- gitShow5

- 1c83a7b4d5bc21bff88b0a798385f5a8e581cc66

- Crystal Cave

- Score

- Ascent.aif

**Comment by michaelpalumbo** [comment]
- gitShow1
- 24cab10db32d394155773363001c4f4f9a30e8cd
- Main
- Bleat Sampras
- Stevia Buscemi.aif

**Comment by AmirbahadorRostami** [comment]
- gitShow3

- fc781f607fa6281341914ac2aa2b0747239191d2

- thumbel

- score

- "trying to be kieran trying to be Mike Felt.aif"

**Comment by TheDispersionLab** [comment]
“it’s in the git, repeating here"



gitShow7

5a0bc601bb2a2bb8a9785759ebf4f06100a9a03f

dvnt-gitshow-week2.maxpat

5.pdf

newsy.aif

**Comment by audiobeing** [comment]
gitshow2
75a0f401bcdf3ccf516bc24a2fdaf7e080ff683f
2 finger grain play
stumbling through micro movement
2fingerGrainPlay.aif
