### ISSUE TITLE
add images to reflections.md

### ISSUE THREAD

**Issue by lorenaSalome** [dispersionlab/gitshow#14]
@michaelpalumbo can we add images to the reflections file? if yes, Can i then upload the images to my branch? Now I have the file with images pointing to my local drive. Thanks!

**Comment by michaelpalumbo** [comment]
Hi @lorenaSalome -- I hope I'm getting this to you soon enough!

Great question! What if you created a new folder in the repo, and called it 'extensions'. Then, in the markdown image link you can use relative path syntax:

```markdown
![image name or some text or whatever](extensions/recording2.png)
```

For reference, this github user demonstrates in better detail: 

https://github.com/mark-anders/relative-image-url

**Comment by michaelpalumbo** [comment]
@lorenaSalome I'll just qualify that I gave the folder name some consideration before deciding on 'extensions'. it could be called 'images', but I want to assume that others might decide to include other types of assets, and the notion of 'extensions' fits within the literature of distributed creativity/distributed cognition

**Comment by lorenaSalome** [comment]
@michaelpalumbo I will create a folder called extensions then. thanks!

**Comment by michaelpalumbo** [comment]
@lorenaSalome wonderful. I'm going to close this issue now :)

**Comment by michaelpalumbo** [comment]
note, added this to the wiki https://github.com/dispersionlab/gitshow/wiki/embedding-content-a-markdown-file
