### ISSUE TITLE
suggestions for altering README.md

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow#15]
So @reginalluna you made changes to README.md. I appreciate that you made the effort to improve the clarity of one of the sections. However, as per the first section in the README.md, it's important to me that you **only make changes to the 5 files* listed near the top of the README.md document (recording, score, reflections, patch, module). Any other file should be considered an administrative file, and I alone am the one to make changes. 

That said I don't want to discourage you from making *suggestions* for improvements, I only ask that you do so by posting it as a new issue in the [primary gitshow issues threads](https://github.com/dispersionlab/gitshow/issues), where we can discuss it and I can then make sure that the change is applied across all repositories. 

Ok, so here are the commits referencing the changes you made to README.md 

https://github.com/dispersionlab/gitshow11/commit/a6c7d57
https://github.com/dispersionlab/gitshow11/commit/632808e
https://github.com/dispersionlab/gitshow11/commit/835b39a
https://github.com/dispersionlab/gitshow11/commit/b6a0212

Resulting in 2 changes: 

#### the addition of the following text, starting at line 25:

> **Open Terminal** 
> ```shell
> cd  PATH/the repository
> ```
> **Initialized the repository on Terminal**
> ```shell
> git init
> ```

The problem is that this is only partially correct. I certainly do not want anyone to initialize a repository, at least not for *gitshow*... What we want to do after changing the working directory in the terminal (the 'cd' command), is to then clone the repository from the github link. Details on how to clone are found in the [primary gitshow wiki](https://github.com/dispersionlab/gitshow/wiki/using-git#clone)

So with this in mind, I'll make sure that between last week and this week that all README.md files have a note stating that the git commands are available for reference in the wiki. 

#### changes made starting at line 45:

> 	```shell
> 	git commit -am "beginning to reflect on the score and recording"
> 	```
> 	**if the error message shows up
> 	```shell
> 	nothing added to commit but untracked files present
> 	```
> 	**then write 
> 	```shell
> 	git add --all
> 	```
> 	**and make a commit again

Other than a very special circumstance as detailed [here](https://github.com/dispersionlab/gitshow/wiki/embedding-content-a-markdown-file) and developed in collaboration with @lorenaSalome in issue #14 , there should be no situation in which untracked files are present. If untracked files are appearing beyond that special circumstance, please open a new git issue and tell me about it. 

@reginalluna assuming you have already cloned the repo, you will now need to pull my changes to the README.md into your repo before pushing. The wiki article on git also has details on how to do this.

**Comment by reginalluna** [comment]
Oh, get it.

Because the commit of the changes of the scripts didn't work on Terminal
until I initialised it. I wrote there just want to tell people that there's
one of the solutions if they face the same problem. Kkk, I will just mark
it on my own notebook and won't touch the file again.

**Comment by michaelpalumbo** [comment]
@reginalluna Hmm, next time you can't commit, can you run 

```shell 
git status
``` 
and post the printout here? 

Also, this [article on git init](https://www.atlassian.com/git/tutorials/setting-up-a-repository/git-init) might interest you, particularly init vs cloning. Its neat that cloning actually involves initialization.

**Comment by michaelpalumbo** [comment]
also 

> I will just mark it on my own notebook and won't touch the file again.

I actually much prefer you to bring it to our attention, as its possible others are experiencing a similar issue :). Yeah, if you can just post *any* problem, bug, idea, feature, etc. in a new issue on this primary github repo, that'd be really appreciated.

**Comment by reginalluna** [comment]
Oh nice, thank you so much, Michael! And I have a question that every time
when I run RACK on my Mac, the sound of my laptop's fan is quite crazy.
Will you have a similar issue on your laptop?

kkk! Maybe I should email you first next time when I find the problem and
provide the solution I have.

**Comment by reginalluna** [comment]
I tried it, but it doesn't work. That's why I used *git init *. I will try
it again tomorrow to see what will happen.

**Comment by michaelpalumbo** [comment]
> Maybe I should email you first next time when I find the problem and
> provide the solution I have.

Honestly, I really want you to post it as a [github issue](https://github.com/dispersionlab/gitshow/issues)

**Comment by michaelpalumbo** [comment]
> I tried it, but it doesn't work. That's why I used *git init *. I will try it again tomorrow to see what will happen.

@reginalluna The deadline for pushing was tonight (sunday) at 11:59pm. Can you still get it in tonight?

**Comment by reginalluna** [comment]
Oh, ok! I will do it now. I thought the deadline is Monday.

**Comment by michaelpalumbo** [comment]
also

> And I have a question that every time when I run RACK on my Mac, the sound of my laptop's fan is quite crazy. Will you have a similar issue on your laptop?

As an example (and because its a different topic but is likely relevant to others, I've opened this as [new issue here](https://github.com/dispersionlab/gitshow/issues/16)

**Comment by michaelpalumbo** [comment]
> I will do it now. I thought the deadline is Monday.

cool, thanks! it gives me time to check for problems or anything interesting to bring up in class :)

**Comment by reginalluna** [comment]
ok cool. Sorry for the delay, there're so many things need to do this
weekend. But will work now
