### ISSUE TITLE
VCV rack causes laptop fan to run hard, optimization options

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow#16]
From @reginalluna:
> ...when I run RACK on my Mac, the sound of my laptop's fan is quite crazy.
> Will you have a similar issue on your laptop?

This has been a well-documented issue within the VCV rack community. The program runs the GPU rather hard. But fortunately there are some ways to curb it. 

- Try changing the frame rate in Rack. click **View > Frame Rate**
- Try changing the number of threads in use click **Engine > Threads**

See also, this thread: 
https://community.vcvrack.com/t/vcv-rack-performance-tips-for-older-macbooks/4654/8
(ignore the 'older macbooks' part. i'm using one of their suggestions on my newer mbp)

**Comment by reginalluna** [comment]
Since I turned the _**Frame Rate**_ down to **_10hz_** The fan didn't make the noise now.

**Comment by michaelpalumbo** [comment]
Wonderful!

**Comment by michaelpalumbo** [comment]
@JacobDotCram here's the thread I was referring to

**Comment by jcrmxyz** [comment]
@michaelpalumbo Thanks! Turns out it was running on 1 thread. Hopefully that fixes things.

**Comment by michaelpalumbo** [comment]
> @michaelpalumbo Thanks! Turns out it was running on 1 thread. Hopefully that fixes things.

Cool. Please post the result here for others :)

**Comment by michaelpalumbo** [comment]
Note that this is now documented in the wiki. https://github.com/dispersionlab/gitshow/wiki/Optimizing-VCV-Rack
