### ISSUE TITLE
github markdown doesn't support embedding videos

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow#18]
Hi @lorenaSalome I love that you tried to embed a video in your score. that's really cool idea! Unfortunately it seems that it is one of the media types that github's markdown does not support. It is possible to do it in markdown with their hosted website format (github.io pages, see jekyll for more info), but not with our markdown files. 

I would encourage you to visit the live link for the score.md in the repo you work in to test whether your media content embedded properly ( or to your liking). See this link for example, and the broken video embed at the bottom:

https://github.com/dispersionlab/gitshow12/blob/master/score.md

**Comment by michaelpalumbo** [comment]
alternately, you could try turning your video into a gif. 

I did so [here](https://github.com/dispersionlab/gitshow/wiki/embedding-content-a-markdown-file)

**Comment by michaelpalumbo** [comment]
@lorenaSalome any changes? I need to reassign the repository soon.

**Comment by lorenaSalome** [comment]
@michaelpalumbo Sorry for my late response. I put a gif file and it works. Thank you!

**Comment by michaelpalumbo** [comment]
excellent! I saw that last night, thanks!
