### ISSUE TITLE
unable to push

### ISSUE THREAD

**Issue by pooneh7318** [dispersionlab/gitshow#24]
Hi @michaelpalumbo 
it is 11:56 now and github won't let me push my changes to master.

**Comment by pooneh7318** [comment]
remote: Permission to dispersionlab/gitshow13.git denied to pooneh7318.

**Comment by michaelpalumbo** [comment]
I think you need to accept the invitation for write privileges for the repo. Check your email or try notifications in github. We might have to do this for your account every week.
On Jan 19, 2020, 11:57 PM -0500, poonehmg <notifications@github.com>, wrote:
	remote: Permission to dispersionlab/gitshow13.git denied to pooneh7318.

**Comment by michaelpalumbo** [comment]
@pooneh7318 Did this work for you?

**Comment by pooneh7318** [comment]
Yes @michaelpalumbo, I pushed everything yesterday
