### ISSUE TITLE
How to keep working/rehearsing after the weekly push?

### ISSUE THREAD

**Issue by rekdtech** [dispersionlab/gitshow#25]
Hey @michaelpalumbo can you remind me what needs to be done so that I can keep playing with the instrument after the weekly push?  (Is there a specific name for the new branch and will I still be able to create one if the permissions have been changed?)  Thanks!

**Comment by michaelpalumbo** [comment]
Hi @rekdtech -- you can name the branch anything you want. See either step 2 or 3 of this article for how to create a new branch: https://github.com/dispersionlab/gitshow/wiki/in-class-procedures

You'll be able to push the new branches at the end of the class :)
On Jan 20, 2020, 9:18 AM -0500, rekdtech <notifications@github.com>, wrote:
	Hey @michaelpalumbo can you remind me what needs to be done so that I can keep playing with the instrument after the weekly push? (Is there a specific name for the new branch and will I still be able to create one if the permissions have been changed?) Thanks!
