### ISSUE TITLE
please report any problems with process // software

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow#7]
please report problems experienced with with the git show process, instructions/readme.ms, git, or vcv rack here. 

just want to note here that i reported the bug with the prototype module not re-instancing updated .js code when on new filepath https://github.com/VCVRack/VCV-Prototype/issues/22

**todo** @michaelpalumbo needs to report the problem with the vcv-recorder module where it won't let you record when operating in loaded sessions (i.e. adding a recorder module, when pressing record it works fine, but upon reopening rack (after closing for whatever the reason), the record button no longer responds (stays grey when clicking). I think this is related to the above-mentioned issue 22, as I *think* the .vcv file containing the recorder module had been copied to another path (duplicated from gitshow1, probably.) 

**todo** @michaelpalumbo needs to report the problem with the vcv-recorder module where it won't prompt for filename/path each time you go to record. maybe this is part of its design, but it doesn't suit your needs.

**Comment by roryhoy** [comment]
Rack can't find modules "Rampage" of plugin "Befaco" and "Recorder" of plugin "VCV-Recorder" from the initial installation.

Getting plugins Befaco and VCV-Recorder from the vcv download page solved this!

**Comment by michaelpalumbo** [comment]
> Getting plugins Befaco and VCV-Recorder from the vcv download page solved this!

@roryhoy thanks for including what worked for you. I'll be sure to add this to the Readme.md setup instructions.
