### ISSUE TITLE
end-of-session improvisation thread

### ISSUE THREAD

**Issue by michaelpalumbo** [dispersionlab/gitshow#9]
So we have a meetup in the dispersion lab (room CFA 334 @ York) on the last Thursday of each session, at 12pm-1pm. I'm going to use this thread to keep track of who can attend each session, so please reply to this thread with 'yes' or 'no' to indicate if you'll you'll be attending a given meetup. Please bring your laptop with you.

**Comment by michaelpalumbo** [comment]
**Thursday, November 14 @12pm (_Session 2_):**
Please tag @palumbalumbo in your reply so I can keep track if you're attending or not.  

Michael Palumbo - coming
@dvntsea -  coming
@magfoto 
@roryhoy - coming
@reginalluna -  coming

**Comment by reginalluna** [comment]
#GET

**Comment by michaelpalumbo** [comment]
> #GET

I don't understand this reply, is there something I should respond to?

**Comment by michaelpalumbo** [comment]
> #GET

thanks @reginalluna I now have you marked as attending.

**Comment by roryhoy** [comment]
Yes!

**Comment by michaelpalumbo** [comment]
Session 3 Improvisation event: Thursday, November 28 @12pm-1pm, Dispersion Lab rm CFA334

Participants, please reply yes/no whether you'll be attending the *session3 improvisation* 
@roryhoy - 
Doug - yes
@hrysovalanti - 
@audiobeing - 
Michael - yes

**Comment by hrysovalanti** [comment]
yes

**Comment by hrysovalanti** [comment]
yes

**Comment by roryhoy** [comment]
yes
